Fix check_freecad_version() failing on 'Unknown' git version
On some distros, the FreeCAD `App.Version()` function does not know what
git revision it was built from and thus returns the following tuple:

	[1, 0, 0, 'Unknown', 'Unknown', 'Unknown']

The way `check_freecad_version()` was written, this would fail:

	ValueError: invalid literal for int() with base 10: 'Unknown'

Make the function fall back to a sane number (0) when it cannot parse
the git version string.